### ISSUE TITLE
Crash editing js functions

### ISSUE THREAD

**Issue by braquino** [gorules/jdm-editor#104]
Version: 1.20.5
Builder: Vite 5.4 (with sass-embedded 1.80)
Node 22.4.1

How: From blank canvas, add a Function an click: "edit function"

React code:
``` jsx
<div className="" style={{ height: 600 }}>
  <JdmConfigProvider>
    <DecisionGraph value={graph} onChange={(val) => setGraph(val)} style={{ height: 600 }} />
  </JdmConfigProvider>
</div>
```

Graph object when clicked "Edit Function"
``` json
{
    "nodes": [
        {
            "type": "functionNode",
            "content": {
                "source": "import zen from 'zen';\n\n/** @type {Handler} **/\nexport const handler = async (input) => {\n  return input;\n};\n"
            },
            "id": "4be5b4e1-6100-4720-ac5e-d4e481ecc5bf",
            "name": "function1",
            "position": {
                "x": 280,
                "y": 160
            }
        }
    ],
    "edges": []
}
```

Error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'variabletype_fromJson')
    at _VariableType.fromJson (chunk-YJYMPD56.js?v=24283913:92894:22)
    at createVariableType (chunk-YJYMPD56.js?v=24283913:93050:25)
    at chunk-YJYMPD56.js?v=24283913:193618:19
    at commitHookEffectListMount (chunk-RY6NLCXT.js?v=24283913:16915:34)
    at commitPassiveMountOnFiber (chunk-RY6NLCXT.js?v=24283913:18156:19)
    at commitPassiveMountEffects_complete (chunk-RY6NLCXT.js?v=24283913:18129:17)
    at commitPassiveMountEffects_begin (chunk-RY6NLCXT.js?v=24283913:18119:15)
    at commitPassiveMountEffects (chunk-RY6NLCXT.js?v=24283913:18109:11)
    at flushPassiveEffectsImpl (chunk-RY6NLCXT.js?v=24283913:19490:11)
    at flushPassiveEffects (chunk-RY6NLCXT.js?v=24283913:19447:22)
```

And then:
```
The above error occurred in the <Ra> component:

    at Ra (http://localhost:3000/node_modules/.vite/deps/chunk-YJYMPD56.js?v=24283913:193578:13)
    at Suspense
    at Xr (http://localhost:3000/node_modules/.vite/deps/chunk-YJYMPD56.js?v=24283913:191238:17)
    at div
    at div
    at http://localhost:3000/node_modules/.vite/deps/chunk-YJYMPD56.js?v=24283913:191311:47
    at div
    at http://localhost:3000/node_modules/.vite/deps/chunk-YJYMPD56.js?v=24283913:191289:67
    at Lo (http://localhost:3000/node_modules/.vite/deps/chunk-YJYMPD56.js?v=24283913:184872:21)
    at ReactFlowProvider (http://localhost:3000/node_modules/.vite/deps/chunk-YJYMPD56.js?v=24283913:92081:28)
    at div
    at http://localhost:3000/node_modules/.vite/deps/chunk-YJYMPD56.js?v=24283913:191328:15
    at MotionWrapper (http://localhost:3000/node_modules/.vite/deps/chunk-YJYMPD56.js?v=24283913:34266:5)
    at ProviderChildren (http://localhost:3000/node_modules/.vite/deps/chunk-YJYMPD56.js?v=24283913:34371:5)
    at ConfigProvider (http://localhost:3000/node_modules/.vite/deps/chunk-YJYMPD56.js?v=24283913:34651:27)
    at Na (http://localhost:3000/node_modules/.vite/deps/chunk-YJYMPD56.js?v=24283913:193751:10)
    at div
    at div
    at div
    at RuleEngine (http://localhost:3000/src/Pages/RuleEngine/index.jsx?t=1729246768034:30:41)
    at RenderedRoute (http://localhost:3000/node_modules/.vite/deps/chunk-ZXSMJV3H.js?v=24283913:4062:5)
    at Routes (http://localhost:3000/node_modules/.vite/deps/chunk-ZXSMJV3H.js?v=24283913:4571:5)
    at div
    at div
    at App (http://localhost:3000/src/App.jsx?t=1729246768034:50:20)
    at RenderedRoute (http://localhost:3000/node_modules/.vite/deps/chunk-ZXSMJV3H.js?v=24283913:4062:5)
    at Routes (http://localhost:3000/node_modules/.vite/deps/chunk-ZXSMJV3H.js?v=24283913:4571:5)
    at Router (http://localhost:3000/node_modules/.vite/deps/chunk-ZXSMJV3H.js?v=24283913:4514:15)
    at BrowserRouter (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=24283913:554:5)
    at MQTTContextProvider (http://localhost:3000/src/Context/mqttConnector.jsx:43:27)
    at SocketContextProvider (http://localhost:3000/src/Context/socketContext.jsx:27:27)
    at ConsoleContextProvider (http://localhost:3000/src/Context/consoleContext.jsx:23:51)
    at LoginContextProvider (http://localhost:3000/src/Context/loginContext.jsx:23:39)
    at CurrentObjsContextProvider (http://localhost:3000/src/Context/currentObjsContext.jsx:24:45)
    at FiltersContextProvider (http://localhost:3000/src/Context/filtersContext.jsx:38:39)
    at UserContextProvider (http://localhost:3000/src/Context/userContext.jsx:23:41)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

**Comment by nimbit-software** [comment]
I have the same issue.

**Comment by billgloff** [comment]
I'm also experiencing this with webpack. Has anyone been able to get around it?

**Comment by stefan-gorules** [comment]
Hi, the issue is likely caused by WASM not being initialized, but being invoked. I've created a PR to solve this.

However we would still strongly suggest that you utilise web assembly as this enables auto-complete and type checking. This can be done differently depending on your bundler. For vite, this is done in straight forward way using https://github.com/gorules/editor/blob/master/vite.config.ts#L8. And then initialising it: https://github.com/gorules/editor/blob/master/src/main.tsx#L26.

**Comment by braquino** [comment]
> Hi, the issue is likely caused by WASM not being initialized, but being invoked. I've created a PR to solve this.
> 
> However we would still strongly suggest that you utilise web assembly as this enables auto-complete and type checking. This can be done differently depending on your bundler. For vite, this is done in straight forward way using https://github.com/gorules/editor/blob/master/vite.config.ts#L8. And then initialising it: https://github.com/gorules/editor/blob/master/src/main.tsx#L26.

This worked smoothly, thank you @stefan-gorules , you are doing a very good job on gorules, this framework has a bright future.
