### ISSUE TITLE
React 19

### ISSUE THREAD

**Issue by nimbit-software** [gorules/jdm-editor#138]
React 19 introduces some breaking changes with ref (and a few other things). 

This seems to effect the current project. I would be happy to help get that resolved. 

I realize that react 19 is still in RC but nextjs 15 requires it and i think the issues that currently exist 

````
hook.js:608 Accessing element.ref was removed in React 19. ref is now a regular prop. It will be removed from the JSX Element type in a future release. Error Component Stack
    at div (<anonymous>)
    at g (<anonymous>)
    at g (<anonymous>)
    at svg (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
````

````
render.js:51 Uncaught TypeError: reactRender is not a function
    at legacyRender (render.js:51:3)
    at render (render.js:65:3)
    at showWaveEffect (WaveEffect.js:139:68)
    at useWave.useEvent[showWave] [as current] (useWave.js:34:80)
    at eval (useEvent.js:16:114)
    at eval (useWave.js:48:13)
    at callRef (raf.js:34:7)
    at eval (raf.js:38:9)
````

just wanted to makre sure there is no ongoing work on that before i start trying to fingure out what is causing the problem.

**Comment by ivanmiletic** [comment]
We would be happy if you would like to solve it. There is no ongoing big work on JDM Editor

**Comment by nimbit-software** [comment]
Great ill take a look at it and see if i can put something together.

**Comment by supermacro** [comment]
https://github.com/gorules/jdm-editor/pull/189
